GET http://localhost:8080/api/dog/1
Accept: application/json

###
POST http://localhost:8080/api/dog
Content-Type: application/json

{"name": "Sirion",
  "age": 6,
  "breed": "Mudi",
  "gender": "SIRE",
  "lastWalkString": "2021-08-03 16:00:00",
  "hasWaterAndFood": true,
  "goneStray": false
}
###
POST http://localhost:8080/api/dog
Content-Type: application/json

{"name": "Diego",
  "age": 11,
  "gender": "SIRE",
  "breed": "Máltai",
  "goneStray": false
}
###
PUT http://localhost:8080/api/dog/2
Content-Type: application/json

{"name": "Diego",
  "age": 13,
  "gender": "SIRE",
  "breed": "Máltai",
  "goneStray": false
}
###
DELETE http://localhost:8080/api/dog/2
Content-Type: application/json

###
PUT http://localhost:8080/api/dog/find/2
Content-Type: application/json

###
GET http://localhost:8080/api/dog
Accept: application/json

###
