POST http://localhost:8080/api/dog/adopt/2
Content-Type: application/json

###
GET http://localhost:8080/api/
Accept: application/json

### List all animals
GET http://localhost:8080/dog/bestfriend/1
Accept: application/json

### Get the best friend of dog with ID 1
GET http://localhost:8080/api/dog/walk
Accept: application/json

### Walk all dogs, who need it
GET http://localhost:8080/api/dog/1
Accept: application/json

### Find dog with ID
POST http://localhost:8080/api/dog
Content-Type: application/json

{"name": "Sirion",
  "age": 6,
  "breed": "Mudi",
  "gender": "SIRE",
  "hasWaterAndFood": true,
  "adopted": false
}
### Create Sirion

POST http://localhost:8080/api/cat
Content-Type: application/json

{"name": "Lucifer",
  "age": 10,
  "breed": "Giant",
  "gender": "TOM",
  "hasWaterAndFood": true,
  "adopted": false
}
### Create Lucifer
POST http://localhost:8080/api/dog
Content-Type: application/json

{"name": "Diego",
  "age": 13,
  "breed": "Máltai",
  "gender": "SIRE",
  "hasWaterAndFood": true,
  "adopted": false
}
### Create Diego
PUT http://localhost:8080/api/dog/2
Content-Type: application/json

{"name": "Diego",
  "age": 11,
  "gender": "SIRE",
  "breed": "Máltai",
  "hasWaterAndFood": true,
  "adopted": false
}
### Update Diego to correct age
DELETE http://localhost:8080/api/dog/2
Content-Type: application/json

### Delete dog with ID 2
PUT http://localhost:8080/api/dog/walk/1
Content-Type: application/json

###  Walk dog with ID 1
GET http://localhost:8080/api/dog
Accept: application/json

### List all dogs
